name: obj_edit_annotation
description: Classes and helper functions that support widget code generation via the
  `obj_edit_gen` package.
version: 0.0.1 
repository: https://github.com/driftboat/flutter_obj_editor/tree/main/obj_edit_annotation

environment:
  sdk: ">=2.12.0 <3.0.0"
