name: obj_edit_gen
description:  Automatically generate code for converting to widget by annotating
  Dart classes.
version: 1.0.0
repository: https://github.com/driftboat/flutter_obj_editor/tree/main/obj_edit_gen

environment:
  sdk: ">=2.12.0 <3.0.0" 

dependencies: 
 source_gen: ^1.0.0
 obj_edit_annotation: ^1.0.0
 build: ^2.0.0
 build_config: ^1.0.0   

dev_dependencies: 
  build_runner: ^2.0.0
  source_gen_test: ^1.0.0
  test: ^1.16.0