name: obj_edit_gen
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0" 

dependencies: 
 source_gen: ^1.0.0
 obj_edit_annotation:
    path: ../obj_edit_annotation/

dev_dependencies: 
  build_runner: ^2.0.0
  source_gen_test: ^1.0.0
  build_config: ^1.0.0
  test: ^1.16.0